"""move duration_minutes to activity

Revision ID: b2212f37ba36
Revises: ea27a82bd8ff
Create Date: 2026-08-03 17:37:49.636217

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2212f37ba36'
down_revision: Union[str, Sequence[str], None] = 'ea27a82bd8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.drop_column('divedetail', 'duration_minutes')
    op.drop_column('yogadetail', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogadetail', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('divedetail', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('activity', 'duration_minutes')
    # ### end Alembic commands ###
