"""add generated_plan table

Revision ID: b9a3727ea75f
Revises: b2212f37ba36
Create Date: 2026-08-04 11:26:35.101251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9a3727ea75f'
down_revision: Union[str, Sequence[str], None] = 'b2212f37ba36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generatedplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('focus_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upcoming_event', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sessions', sa.JSON(), nullable=True),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notion_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generatedplan')
    # ### end Alembic commands ###
