"""split climb and strength into sessions and detail tables

Revision ID: dd1e8426e0e4
Revises: 2af6dd36458d
Create Date: 2026-07-26 13:19:22.559147

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1e8426e0e4'
down_revision: Union[str, Sequence[str], None] = '2af6dd36458d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climbsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('gym', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strengthsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('body_area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('climb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('climb_session_id', sa.Integer(), nullable=False),
    sa.Column('grade_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_normalized', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['climb_session_id'], ['climbsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strength_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['strength_session_id'], ['strengthsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('strengthdetail')
    op.drop_table('climbdetail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climbdetail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gym', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grade_raw', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grade_normalized', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('climbdetail_activity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('climbdetail_pkey'))
    )
    op.create_table('strengthdetail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body_area', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('strengthdetail_activity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('strengthdetail_pkey'))
    )
    op.drop_table('exercise')
    op.drop_table('climb')
    op.drop_table('strengthsession')
    op.drop_table('climbsession')
    # ### end Alembic commands ###
