"""add notion_page_id to activity

Revision ID: ea27a82bd8ff
Revises: dd1e8426e0e4
Create Date: 2026-07-29 00:06:59.239474

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('notion_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_activity_notion_page_id'), 'activity', ['notion_page_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_notion_page_id'), table_name='activity')
    op.drop_column('activity', 'notion_page_id')
    # ### end Alembic commands ###
